[package]
name = 'Cetue-AMM'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'a58060f88d66b90a0548a506e22270b04a328db3'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
cetus_amm = "_"
